version: 2.1
workflows:
  testing:
    jobs:
      - vm_service_test
      # - docker_layer_cache_test

jobs:
  vm_service_test: # name of your job
    machine: true # run on 'VM service' Linux VM
    steps:
      - run:
          name: VM Service VM
          command: hostname -f 
