version: 2.1
workflows:
  docker:
    jobs:
      - lambda
      
jobs:
  lambda:
    machine: true
    resource_class: ci-namespace/aws-lambda-medium
    steps:
      - run:
          command: print("Hi I'm on AWS Lambda with Python!")
          shell: /usr/bin/python