version: 2.1
workflows:
  docker:
    jobs:
      - lambda
      
jobs:
  lambda:
    machine: true
    resource_class: ci-namespace/aws-lambda-medium
    steps:
      - run: echo "Hi I'm on AWS Lambda!"