version: 2.1
workflows:
  windows:
    jobs:
      - AWS
      - Azure
      - GCP
      
jobs:
  AWS:
    machine: true
    resource_class: ci-namespace/aws-ec2-medium-windows
    steps:
      - run: 
          command: 'Write-Host ''Hello, I am on Windows! in Google Cloud Compute'''
          shell: powershell.exe
  Azure:
    machine: true
    resource_class: ci-namespace/azure-vm-medium-windows
    steps:
      - run: 
          command: 'Write-Host ''Hello, I am on Windows! in Google Cloud Compute'''
          shell: powershell.exe
  GCP:
    machine: true
    resource_class: ci-namespace/gcp-cc-medium-windows
    steps:
      - run: 
          command: 'Write-Host ''Hello, I am on Windows! in Google Cloud Compute'''
          shell: powershell.exe