version: 2.1
workflows:
  testing:
    jobs:
      - ec2
      
jobs:
  ec2:
    machine: true
    resource_class: ci-namespace/aws-ec2-medium-windows
    steps:
      - run: Write-Host "Hi I'm on Windows! in AWS Elastic Cloud Compute !"