version: 2.1

jobs:
  build-tag-deploy:
    # machine: true
    docker:
      - image: cimg/base:2021.02-20.04
    steps:
      # Checkout the code as the first step.
      - checkout
      # Build, Tag, Deploy
      - setup_remote_docker
      - run:
          name: Build
          command: docker build -t path-circleci-sample-docker-image .
      - run:
          name: Tag
          command: docker tag path-circleci-sample-docker-image $CI_REGISTRY/path/path-circleci-sample-docker-image
      - run:
          name: Deploy
          command: |
            echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
            docker push $CI_REGISTRY/path/path-circleci-sample-docker-image
workflows:
  build:
    jobs:
      - build-tag-deploy:
          context: sample_context
